# -*- coding: utf-8 -*-
"""BLEU

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uwp4Fzm-R5EUdYwWZW52SYSF3x7HefNV
"""

pip install nltk

import json
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
import csv

with open("/content/data.json", "r") as f:
    input = json.load(f)

with open("/content/output.json", "r") as f:
    output = json.load(f)

from os import getenv
smooth = SmoothingFunction().method4

bleu_scores = []

bleu_data = []

for out in output:
    dish_title = out["dish_title"]
    generated = out["generated_recipe"]

    inp = next((i for i in input if i["title"] == dish_title), None)
    if not inp:
        continue

    reference = inp["recipe"]

    bleu = sentence_bleu([reference.split()], generated.split(), smoothing_function=smooth)
    bleu_scores.append(bleu)

    bleu_data.append([dish_title, reference, generated, bleu])

    with open("bleu_results.csv", "w", newline="") as f:
      writer = csv.writer(f)
      writer.writerow(["Dish Title", "Manually written recipe", "Predicted Recipe", "BLEU Score"])
      writer.writerows(bleu_data)


    print(f"\n Dish Title: {dish_title}")
    print(f"\n Reference:  {reference}")
    print(f"\nPredicted:  {generated}")
    print(f"\nBLEU: {bleu:.4f}")

from google.colab import files

files.download("bleu_results.csv")